const {Arg} = require('../api-dialect')

/**
 * 获取 models 中的属性, 自动生成初版的 args
 * @param {object} model
 * @param {boolean} readOnly
 * @return {array}
 */

exports.argsFactory = (model, method = 'post') => {
  let attributes = model.rawAttributes
  let args = []

  Object.keys(attributes).forEach(k => {
    let v = attributes[k]

    if (method === 'post' || method === 'put') {
      if (v.hasOwnProperty('readOnly') && v.readOnly) {
        return undefined
      }

      if (
        method === 'post' &&
        (
          v.primaryKey && v.type.constructor.name === 'Constructor' ||
          v.hasOwnProperty('_autoGenerated')
        )
      ) {
        return undefined
      }

      if (
        method === 'put' &&
        v.hasOwnProperty('_autoGenerated')
      ) {
        return undefined
      }
    }
    let arg = new Arg(k, false)

    if (v.hasOwnProperty('allowNull') && !v.allowNull) {
      arg.setRequired()
    }

    if (v.hasOwnProperty('defaultValue')) {
      arg.setDefault(v.defaultValue)
    }

    if (v.values && v.values.length !== 0) {
      arg.setRange(v.values)
    }

    if (v.type.key === 'DECIMAL') {
      arg.type = 'number'
    }

    if (v.type.key === 'INTEGER') {
      arg.type = 'integer'
    }

    if (v.type.key === 'DATEONLY') {
      arg.setDateFormat('YYYY-MM-DD')
    }

    if (v.type.key === 'DATE') {
      arg.setDateFormat('YYYY-MM-DD HH:mm:ss')
    }

    args.push(arg)

    return undefined
  })

  return args
}
